### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by elpaxel** [julianrubisch/express-asset-file-cache-middleware#11]
Ty for good library but I have a question. Why are you creating 3 directories from the hash. I don't get it. Because if it is due to duplicates then one sha256 hash as the directory would be enough I think. So what is the deal with this 3 nested folders ?

**Comment by julianrubisch** [comment]
Has to do with lookup speed. You can view it like a clustered DB index: 

When structured like a tree, you look for the first 2 characters, then the next 2 characters, then the whole string in what is a substantially smaller set of files than for the flat list case.

Look at it this way: say you have 10000 cached files and are referencing the last one: in the flat list case, the worst case is traversing 9999 list items before you hit the correct one.

Chop off two characters, the list of directories to look at will be dozens, not thousands, worst case, and in the deepest directory, you’ll also probably only end up with a couple of files. Right?

TBH I’ve more or less copypasta’d this from Rails’ local disk cache, but the rationale is pretty well documented there.

**Comment by elpaxel** [comment]
@julianrubisch Thanks for the explanation. I thought about it, but then I did not find any "partial hash search" methods or any use of hash parts in this library, and I thought I was mistaken.
If you still actively maintaining this library then maybe you can add files re-download based on time (maxAge). Basically if file is older then a week then download it again. Something like that.

**Comment by julianrubisch** [comment]
@elpaxel if you still need that functionality, could you please open a separate ticket? thanks!
